name: Hourly Scraper

on:
  schedule:
    - cron: "0 * * * *"  # every hour on the hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        if: ${{ inputs.skip_python_setup != 'true' }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        if: ${{ inputs.skip_dependencies != 'true' }}
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xzf geckodriver-v0.33.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/geckodriver

      - name: Setup Firefox in headless mode
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &


      - name: Run Scraper Script with Debugging
        run: |
          export DISPLAY=:99
          python Test3.py > debug.log 2>&1 || true
          echo "Script failed; uploading logs for debugging."

      - name: Upload Debug Logs
        if: always() # Ensures this step always runs
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs
          path: debug.log
