name: Hourly Scraper Windows

on:
  schedule:
    - cron: "12 * * * *"  # every hour on the hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        if: ${{ inputs.skip_python_setup != 'true' }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        if: ${{ inputs.skip_dependencies != 'true' }}
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install requests
          pip install tzdata
          pip install zoneinfo
          choco install firefox --no-progress
          Invoke-WebRequest -Uri https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-win64.zip -OutFile geckodriver.zip
          Expand-Archive geckodriver.zip -DestinationPath $PWD
          $env:PATH += ";$PWD"

      - name: Run Scraper Script with Debugging
        run: |
          python Test3.py || echo "Script failed"
          
      - name: Set artifact date
        id: artifact_date
        shell: bash
        run: |
          echo "TIMESTAMP_PST=$(TZ='America/Los_Angeles' date '+%Y-%m-%d_%H-%M')" >> "$GITHUB_ENV"
          echo "date=$(TZ='America/Los_Angeles' date '+%Y-%m-%d_%H-%M')" >> "$GITHUB_OUTPUT"

      - name: Upload CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cards-main-${{ steps.artifact_date.outputs.date }}
          path: "**/*_Cards_Main.csv"

      - name: Upload Debug Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs-${{ steps.artifact_date.outputs.date }}
          path: "**/debug_*.log"
