name: Hourly Scraper

on:
  schedule:
    - cron: "0 * * * *"  # every hour on the hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xzf geckodriver-v0.33.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Run Scraper Script
        run: |
          python Test3.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraped-cards-csv
          path: _Cards_Main.csv
