name: Hourly Scraper

on:
  schedule:
    - cron: "0 * * * *"  # every hour on the hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y firefox firefox-geckodriver

      - name: Run Scraper Script
        run: |
          python Test3.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v3
        with:
          name: scraped-cards-csv
          path: _Cards_Main.csv
