name: Scheduled Scrape

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox firefox-geckodriver

      - name: Install Python deps
        run: pip install selenium

      - name: Run scraper
        run: python Test3.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: cards-data
          path: _Cards_Main.csv

